### PR TITLE
cache HCaptcha client

### LINKED ISSUE #18: Cannot log in
I can't log in, idk why. What I know is I have a working internet connection. And to register button does not working, I think it just there as a display. Need to rework and stabilize the application. I love the concept and the lightness of it. I hope these matter will soon be fixed.

### PR DESCRIPTION
**Pull request by X1nto**
Fixes #18

### CODE REVIEW

**Review by DiamondMiner88 — APPROVED** [review]

File: app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt [hunk 1]
```diff
@@ -1,26 +1,37 @@
...
         super.onCreate(savedInstanceState)
-        HCaptcha.getClient(this).setup()
         setContent {
             OpenCordTheme {
                 val systemUiController = rememberSystemUiController()
                 val useDarkIcons = false
+                val useDarkTheme = isSystemInDarkTheme()
                 val surface = MaterialTheme.colorScheme.surface
 
+                val hCaptchaConfig = HCaptchaConfig.builder()
```
Comment (X1nto) [inline app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt:28]: I doubt it's a good idea to do this inside the composable scope, move it outside, just like how it was in line 17 previously.

Comment (wingio) [reply app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt:28]: could it be injected?

Comment (X1nto) [reply app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt:28]: Quite possibly yes, the builder could be provided via DI and then setup could be run before setContent()

also inject deez nuts lmao gotem

File: app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt [hunk 2]
```diff
@@ -33,4 +44,7 @@ class LoginActivity : AppCompatActivity() {
         }
     }
 
-}
\ No newline at end of file
+}
+
+val Context.hCaptcha: HCaptcha
```
Comment (X1nto) [inline app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt:49]: this could be provided via DI

File: app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt (hunk 1 above)
Comment (ItzOnlyAnimal) [reply app/src/main/java/com/xinto/opencord/ui/LoginActivity.kt:28]: INJECT DEEZ NUTS lmao

**Review by ItzOnlyAnimal — APPROVED** [review]
provide deez nuts xd

File: app/src/main/java/com/xinto/opencord/di/HttpModule.kt [hunk 3]
```diff
@@ -33,6 +36,14 @@ val httpModule = module {
         }
     }
 
+    fun provideHCaptcha(context: Context): HCaptcha {
```
Comment (X1nto) [inline app/src/main/java/com/xinto/opencord/di/HttpModule.kt:39]: Move this to a separate module as it does not belong to HTTP

Comment (X1nto) [reply app/src/main/java/com/xinto/opencord/di/HttpModule.kt:39]: I just remembered it's my PR and not yours, I'll do it myself lmao

>DN

File: app/src/main/java/com/xinto/opencord/ui/screen/Login.kt [hunk 4]
```diff
@@ -102,14 +105,13 @@ fun LoginScreen(
...
-            .getClient(context)
-            .verifyWithHCaptcha(viewModel.captchaSiteKey)
+        hCaptcha.verifyWithHCaptcha()
             .addOnSuccessListener {
                 viewModel.login(it.tokenResult)
             }
             .addOnFailureListener {
-                //TODO
+                //TODO do more than just showing a toast i guess
+                Toast.makeText(context, "Captcha failed, try again", Toast.LENGTH_LONG).show()
```
Comment (DiamondMiner88) [inline app/src/main/java/com/xinto/opencord/ui/screen/Login.kt:114]: Shouldn't you retry keep retrying here?

Comment (X1nto) [reply app/src/main/java/com/xinto/opencord/ui/screen/Login.kt:114]: I kinda don't know how to implement that so let's just leave it like this for now

Comment (ItzOnlyAnimal) [reply app/src/main/java/com/xinto/opencord/ui/screen/Login.kt:114]: i suppose you can just trigger it again with .verifyWithHCaptcha

Comment (X1nto) [reply app/src/main/java/com/xinto/opencord/ui/screen/Login.kt:114]: That seems a bit recursive, it might look bad in compose too

**Review by DiamondMiner88 — DISMISSED** [review]
I can't test this since my account is already phone verified (no captcha) however it looks good

**Comment by X1nto** [comment]
I noticed that getClient() always returns a new client, meaning we need to implement the client inside the DI (or assign it to a global static variable but that's meh)

File: app/src/main/java/com/xinto/opencord/di/HCaptcha.kt [hunk 5]
```diff
@@ -0,0 +1,21 @@
...
+    fun provideHCaptcha(activity: Context): HCaptcha {
+        val config = HCaptchaConfig.builder()
+            .siteKey(BuildConfig.CAPTCHA_KEY) // doubt this will ever change
+            .resetOnTimeout(true)
+            .tokenExpiration(1000000L)
+            .build()
+        return HCaptcha.getClient(activity).setup(config)
+    }
+
+    single { params -> provideHCaptcha(params.get()) }
```
[the remark this answers is not in the document]
Comment (X1nto) [reply app/src/main/java/com/xinto/opencord/di/HCaptcha.kt:20]: > Is there a purpose of doing manual params? Doesn't androidContext already get loaded into koin in OpencordApplication?

We need Activity context. androidContext() provides the Application context

**Comment by X1nto** [comment]
fixed
